name: PR Lint
on: pull_request

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install dependencies
        run: |
          npm install --prefix tools/linters
      - name: run linter
        run: |
          cd tools/linters
          find ../../ -type f -name '*.md' -not -path '*/node_modules/*' -exec \
            npx --no-install markdownlint -c tools/linters/markdownlint.json '{}' ';' 2>&1 | tee linter-output
          [ -s linter-output ] && exit 1
